# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2" # this should be changed

package:
  name: "mojo-rustls"
  version: 0.1.1

source:
  - path: ../LICENSE

build:
  script:
    - mkdir -p ${PREFIX}/share/mojo-rustls
    - git clone --depth=1 git@github.com:rustls/rustls-ffi.git
    - cd rustls-ffi && cargo cinstall --library-type=cdylib --destdir=./output
    - ls -la output/usr/local/lib
    - cp output/usr/local/lib/librustls.dylib ${PREFIX}/share/mojo-rustls/librustls.dylib
    - cd .. && rm -R rustls-ffi

about:
  homepage: https://github.com/rustls/mojo-rustls
  license: MIT
  license_file: LICENSE
  summary: Rustls FFI bindings - use Rustls from any language
  repository: https://github.com/rustls/mojo-rustls